# Use a base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the necessary files to the working directory
COPY requirements.txt .
COPY bpp.py .

# Install dependencies
RUN pip install -r requirements.txt

# Execute your Python script
CMD ["python", "-u", "bpp.py"]
